# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-26 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscr', '0021_auto_20170724_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='img_photo',
            field=models.ImageField(blank=True, upload_to='static/cscr/img/'),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='photo280_400',
            field=models.ImageField(blank=True, upload_to='static/cscr/img/'),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='photo280_400_2',
            field=models.ImageField(blank=True, upload_to='static/cscr/img/'),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='photo450_300',
            field=models.ImageField(blank=True, upload_to='static/cscr/img/'),
        ),
        migrations.AlterField(
            model_name='database',
            name='img_photo',
            field=models.ImageField(blank=True, upload_to='static/cscr/img/'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='img_photo',
            field=models.ImageField(blank=True, upload_to='static/cscr/img/'),
        ),
        migrations.AlterField(
            model_name='people',
            name='img_photo',
            field=models.ImageField(blank=True, upload_to='static/cscr/img/'),
        ),
        migrations.AlterField(
            model_name='people_administrator',
            name='img_photo',
            field=models.ImageField(blank=True, upload_to='static/cscr/img/'),
        ),
        migrations.AlterField(
            model_name='people_committee',
            name='img_photo',
            field=models.ImageField(blank=True, upload_to='static/cscr/img/'),
        ),
        migrations.AlterField(
            model_name='people_researcher',
            name='img_photo',
            field=models.ImageField(blank=True, upload_to='static/cscr/img/'),
        ),
        migrations.AlterField(
            model_name='people_scholar',
            name='img_photo',
            field=models.ImageField(blank=True, upload_to='static/cscr/img/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img_photo',
            field=models.ImageField(blank=True, upload_to='static/cscr/img/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='img_photo',
            field=models.ImageField(blank=True, upload_to='static/cscr/img/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
